name: CI
on:
  - push
  - pull_request

jobs:
  Quality Check:
    strategy:
      matrix:
        node-version:
          - 15.x

    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node-version }}-npm
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-npm-

      - name: Lint
        run: npx prettier -c .
