name: CI
on:
  - push
  - pull_request

jobs:
  Quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "*"
          cache: yarn

      - name: Install
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
