name: CI
on:
  - push
  - pull_request

jobs:
  Quality:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - uses: actions/checkout@v2

      - name: Cache NPM
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Lint
        run: npx prettier -c .
